### PR TITLE
fix php 7.2 compatibility

### PR DESCRIPTION
**Pull request by StalkAlex**

### CODE REVIEW

**Comment by handcode** [comment]
For this change, we also need to change the constraint for yiisoft/yii2 to ^2.0.13, because BaseObject did not exist before.

**Comment by schmunk42** [comment]
I am working on a test-setup for 7.2, but I still have issues with several `intl` tests.

**Comment by StalkAlex** [comment]
Should I send you another change for composer.json?

**Comment by schmunk42** [comment]
Yes, please.

**Comment by StalkAlex** [comment]
Done!

**Comment by StalkAlex** [comment]
Audit module will support php 7.2 since 1.1 now.

**Comment by StalkAlex** [comment]
Any updates? @schmunk42 @handcode

**Comment by schmunk42** [comment]
Yeah, sorry for the delay - I am working on a test setup for 7.2

**Comment by schmunk42** [comment]
Fix available in `0.23.0`. Thank you!

**Pull request merged**
